[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
forge-std = "1.9.4"
solady = "0.0.278"
"@solidstate-contracts" = "0.0.60"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
